### ISSUE TITLE
Annoying Mining Issue

### ISSUE THREAD

**Issue by SywardCreed** [GeoRCCraft/Alone#24]
**Describe the bug**
When mining at these specific co-ordinates (if this is a custom world as I think), in this cave. I was mining obsidian of all things when I suddenly was hit with the mining fatigue effect you get in a water temple. I believe the area was a water temple when creating your base world maybe. I was also really so I thought it may be some sort of heat exhaustion, but after waiting 4 minutes about 40 blocks away I got hit again with it. Not exactly where im at but 20 blocks more into the cave. Now I don't know if this is an issue that would be important to you. but I like the modpack, first ive ever played and im really getting into it so I thought id report it. I dont even know if its fixable

**To Reproduce**
1. Go to these co-ordinates
2. Go into cave

**Screenshots**

![screenshot 87](https://user-images.githubusercontent.com/43013867/45115647-7aab9300-b11e-11e8-9842-a1caeb87527d.png)

 - Pack Version (Found in settings menu) [e.g. 1.0.0]

1.0.2

**Comment by GeoRCCraft** [comment]
Please tell me what the seed of this world is?

**Comment by SywardCreed** [comment]
6666666666666666666 

    On ‎Thursday‎, ‎September‎ ‎6‎, ‎2018‎ ‎10‎:‎11‎:‎54‎ ‎AM‎ ‎EDT, GeoRCCraft <notifications@github.com> wrote:  
 
 
Please tell me what the seed of this world is?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avg.com  |

**Comment by GeoRCCraft** [comment]
Only thing I can think of to fix this issue (however I have not been able to replicate it) would be to figure out a way to disable the sea temples. Will be closing this issue now. Thank you :)
